In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer

In [2]:
df = pd.read_csv("brfss_clean.csv")
df

,CHD_OR_MI,SEX,AGE,HEALTH,PHYSICAL_HEALTH,STROKE,BRONCHITIS,KIDNEY_DISEASE,DIABETES,ARTHRITIS,BMI,DIFFICULTY_WALKING,SMOKE,ETHNICITY,SLEEP,ASTHMA,DEPRESSION
0,2.0,2,80,2.0,1.0,2.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,1,8.0,2.0,2.0
1,2.0,2,80,1.0,1.0,2.0,2.0,2.0,3.0,2.0,2657.0,2.0,2.0,1,6.0,2.0,2.0
2,2.0,2,56,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2561.0,2.0,2.0,1,5.0,2.0,2.0
3,2.0,2,73,1.0,1.0,2.0,2.0,2.0,3.0,1.0,2330.0,2.0,1.0,1,7.0,1.0,2.0
4,2.0,2,43,4.0,2.0,2.0,2.0,2.0,3.0,2.0,2177.0,2.0,2.0,1,9.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445127,2.0,2,19,3.0,1.0,2.0,2.0,2.0,3.0,2.0,2563.0,2.0,2.0,2,6.0,1.0,1.0
445128,2.0,2,51,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2866.0,2.0,2.0,2,7.0,2.0,2.0
445129,2.0,2,65,5.0,3.0,2.0,2.0,2.0,3.0,2.0,1723.0,2.0,1.0,2,5.0,2.0,2.0
445130,1.0,1,73,2.0,1.0,2.0,2.0,2.0,3.0,2.0,3255.0,2.0,2.0,2,5.0,1.0,2.0
445131,2.0,1,42,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2260.0,1.0,1.0,2,5.0,2.0,2.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445132 entries, 0 to 445131
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   CHD_OR_MI           440111 non-null  float64
 1   SEX                 445132 non-null  int64
 2   AGE                 445132 non-null  int64
 3   HEALTH              443934 non-null  float64
 4   PHYSICAL_HEALTH     434205 non-null  float64
 5   STROKE              443575 non-null  float64
 6   BRONCHITIS          442913 non-null  float64
 7   KIDNEY_DISEASE      443206 non-null  float64
 8   DIABETES            444045 non-null  float64
 9   ARTHRITIS           442499 non-null  float64
 10  BMI                 396326 non-null  float64
 11  DIFFICULTY_WALKING  421120 non-null  float64
 12  SMOKE               410172 non-null  float64
 13  ETHNICITY           445132 non-null  int64
 14  SLEEP               439679 non-null  float64
 15  ASTHMA              443359 non-null  float64
 16  DEPRESSION          442320 non-null  float64
dtypes: float64(14), int64(3)
memory usage: 57.7 MB

In [4]:
df.isna().sum()

CHD_OR_MI              5021
SEX                       0
AGE                       0
HEALTH                 1198
PHYSICAL_HEALTH       10927
STROKE                 1557
BRONCHITIS             2219
KIDNEY_DISEASE         1926
DIABETES               1087
ARTHRITIS              2633
BMI                   48806
DIFFICULTY_WALKING    24012
SMOKE                 34960
ETHNICITY                 0
SLEEP                  5453
ASTHMA                 1773
DEPRESSION             2812
dtype: int64

In [5]:
df = df.dropna(subset=['CHD_OR_MI'])
df = df.dropna(subset=['BRONCHITIS'])
df = df.dropna(subset=['KIDNEY_DISEASE'])
df = df.dropna(subset=['HEALTH'])
df = df.dropna(subset=['DIABETES'])
df = df.dropna(subset=['ARTHRITIS'])
df = df.dropna(subset=['STROKE'])
df = df.dropna(subset=['PHYSICAL_HEALTH'])
df = df.dropna(subset=['SLEEP'])
df = df.dropna(subset=['ASTHMA'])
df = df.dropna(subset=['DEPRESSION'])

In [6]:
df.isna().sum()

CHD_OR_MI                 0
SEX                       0
AGE                       0
HEALTH                    0
PHYSICAL_HEALTH           0
STROKE                    0
BRONCHITIS                0
KIDNEY_DISEASE            0
DIABETES                  0
ARTHRITIS                 0
BMI                   43726
DIFFICULTY_WALKING    21584
SMOKE                 31632
ETHNICITY                 0
SLEEP                     0
ASTHMA                    0
DEPRESSION                0
dtype: int64

In [7]:
na_variables = ['BMI']

In [8]:
def show_distr(df):
  print("missing values : \n{}".format(df.isna().sum()))
  boxplot = df.boxplot(column=na_variables)  
  hist = df[na_variables].hist(bins=20)
  print("\n -------------------------")

In [9]:
imputer_knn = KNNImputer(n_neighbors=11, weights="uniform")
df_knnimputed = imputer_knn.fit_transform(df)

In [10]:
df.columns

Index(['CHD_OR_MI', 'SEX', 'AGE', 'HEALTH', 'PHYSICAL_HEALTH', 'STROKE',
       'BRONCHITIS', 'KIDNEY_DISEASE', 'DIABETES', 'ARTHRITIS', 'BMI',
       'DIFFICULTY_WALKING', 'SMOKE', 'ETHNICITY', 'SLEEP', 'ASTHMA',
       'DEPRESSION'],
      dtype='object')

In [11]:
df_imputed = pd.DataFrame(df_knnimputed, columns=df.columns)

In [12]:
df_imputed

,CHD_OR_MI,SEX,AGE,HEALTH,PHYSICAL_HEALTH,STROKE,BRONCHITIS,KIDNEY_DISEASE,DIABETES,ARTHRITIS,BMI,DIFFICULTY_WALKING,SMOKE,ETHNICITY,SLEEP,ASTHMA,DEPRESSION
0,2.0,2.0,80.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2918.545455,2.0,2.0,1.0,8.0,2.0,2.0
1,2.0,2.0,80.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0,2657.000000,2.0,2.0,1.0,6.0,2.0,2.0
2,2.0,2.0,56.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2561.000000,2.0,2.0,1.0,5.0,2.0,2.0
3,2.0,2.0,73.0,1.0,1.0,2.0,2.0,2.0,3.0,1.0,2330.000000,2.0,1.0,1.0,7.0,1.0,2.0
4,2.0,2.0,43.0,4.0,2.0,2.0,2.0,2.0,3.0,2.0,2177.000000,2.0,2.0,1.0,9.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415694,2.0,2.0,19.0,3.0,1.0,2.0,2.0,2.0,3.0,2.0,2563.000000,2.0,2.0,2.0,6.0,1.0,1.0
415695,2.0,2.0,51.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2866.000000,2.0,2.0,2.0,7.0,2.0,2.0
415696,2.0,2.0,65.0,5.0,3.0,2.0,2.0,2.0,3.0,2.0,1723.000000,2.0,1.0,2.0,5.0,2.0,2.0
415697,1.0,1.0,73.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,3255.000000,2.0,2.0,2.0,5.0,1.0,2.0
415698,2.0,1.0,42.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2260.000000,1.0,1.0,2.0,5.0,2.0,2.0

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
df_imputed[['SMOKE', 'DIFFICULTY_WALKING']] = imputer.fit_transform(df[['SMOKE', 'DIFFICULTY_WALKING']])

In [14]:
df_imputed

,CHD_OR_MI,SEX,AGE,HEALTH,PHYSICAL_HEALTH,STROKE,BRONCHITIS,KIDNEY_DISEASE,DIABETES,ARTHRITIS,BMI,DIFFICULTY_WALKING,SMOKE,ETHNICITY,SLEEP,ASTHMA,DEPRESSION
0,2.0,2.0,80.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2918.545455,2.0,2.0,1.0,8.0,2.0,2.0
1,2.0,2.0,80.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0,2657.000000,2.0,2.0,1.0,6.0,2.0,2.0
2,2.0,2.0,56.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2561.000000,2.0,2.0,1.0,5.0,2.0,2.0
3,2.0,2.0,73.0,1.0,1.0,2.0,2.0,2.0,3.0,1.0,2330.000000,2.0,1.0,1.0,7.0,1.0,2.0
4,2.0,2.0,43.0,4.0,2.0,2.0,2.0,2.0,3.0,2.0,2177.000000,2.0,2.0,1.0,9.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415694,2.0,2.0,19.0,3.0,1.0,2.0,2.0,2.0,3.0,2.0,2563.000000,2.0,2.0,2.0,6.0,1.0,1.0
415695,2.0,2.0,51.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2866.000000,2.0,2.0,2.0,7.0,2.0,2.0
415696,2.0,2.0,65.0,5.0,3.0,2.0,2.0,2.0,3.0,2.0,1723.000000,2.0,1.0,2.0,5.0,2.0,2.0
415697,1.0,1.0,73.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,3255.000000,2.0,2.0,2.0,5.0,1.0,2.0
415698,2.0,1.0,42.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2260.000000,1.0,1.0,2.0,5.0,2.0,2.0

In [15]:
df_imputed.isna().sum()

CHD_OR_MI             0
SEX                   0
AGE                   0
HEALTH                0
PHYSICAL_HEALTH       0
STROKE                0
BRONCHITIS            0
KIDNEY_DISEASE        0
DIABETES              0
ARTHRITIS             0
BMI                   0
DIFFICULTY_WALKING    0
SMOKE                 0
ETHNICITY             0
SLEEP                 0
ASTHMA                0
DEPRESSION            0
dtype: int64

In [16]:
df_imputed.to_csv('brfss.csv', index=False)