In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data2022.csv")
df

,X_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,X_PSU,CTELENM1,...,X_SMOKGRP,X_LCSREC,DRNKANY6,DROCDY4_,X_RFBING6,X_DRNKWK2,X_RFDRHV8,X_FLSHOT7,X_PNEUMO3,X_AIDTST4
0,1,1,2032022,2,3,2022,1100,2022000001,2022000001,1.0,...,4.0,NaN,2,0.0,1,0,1,1.0,2.0,2.0
1,1,1,2042022,2,4,2022,1100,2022000002,2022000002,1.0,...,4.0,NaN,2,0.0,1,0,1,2.0,2.0,2.0
2,1,1,2022022,2,2,2022,1100,2022000003,2022000003,1.0,...,4.0,NaN,2,0.0,1,0,1,NaN,NaN,2.0
3,1,1,2032022,2,3,2022,1100,2022000004,2022000004,1.0,...,3.0,2.0,2,0.0,1,0,1,9.0,9.0,2.0
4,1,1,2022022,2,2,2022,1100,2022000005,2022000005,1.0,...,4.0,NaN,1,10.0,1,140,1,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445127,78,11,12192022,12,19,2022,1100,2022001527,2022001527,NaN,...,4.0,NaN,7,900.0,9,99900,9,NaN,NaN,1.0
445128,78,11,12212022,12,21,2022,1100,2022001528,2022001528,NaN,...,4.0,NaN,2,0.0,1,0,1,NaN,NaN,1.0
445129,78,11,11292022,11,29,2022,1100,2022001529,2022001529,NaN,...,1.0,NaN,7,900.0,9,99900,9,2.0,2.0,2.0
445130,78,11,12082022,12,8,2022,1100,2022001530,2022001530,NaN,...,4.0,NaN,2,0.0,1,0,1,1.0,1.0,1.0
445131,78,11,12142022,12,14,2022,1100,2022001531,2022001531,NaN,...,3.0,NaN,1,50.0,2,99900,9,NaN,NaN,2.0

In [3]:
brfss_reduced = df[['X_MICHD', 'X_SEX', 'X_AGE80', 'GENHLTH', 'X_PHYS14D', 'CVDSTRK3', 'CHCCOPD3', 
                    'CHCKDNY2', 'DIABETE4', 'HAVARTH4', 'X_BMI5', 'DIFFWALK', 
                    'SMOKE100', 'X_IMPRACE','SLEPTIM1', 'ASTHMA3', 'ADDEPEV3', ']]

In [4]:
columns = ['CHD_OR_MI', 'SEX', 'AGE', 'HEALTH', 'PHYSICAL_HEALTH','STROKE',
       'BRONCHITIS', 'KIDNEY_DISEASE', 'DIABETES', 'ARTHRITIS', 'BMI', 'DIFFICULTY_WALKING', 
           'SMOKE', 'ETHNICITY','SLEEP', 'ASTHMA', 'DEPRESSION']

In [5]:
brfss_reduced.columns = columns
brfss_reduced

,CHD_OR_MI,SEX,AGE,HEALTH,PHYSICAL_HEALTH,STROKE,BRONCHITIS,KIDNEY_DISEASE,DIABETES,ARTHRITIS,BMI,DIFFICULTY_WALKING,SMOKE,ETHNICITY,SLEEP,ASTHMA,DEPRESSION
0,2.0,2,80,2.0,1,2.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,1,8.0,2.0,2.0
1,2.0,2,80,1.0,1,2.0,2.0,2.0,3.0,2.0,2657.0,2.0,2.0,1,6.0,2.0,2.0
2,2.0,2,56,2.0,2,2.0,2.0,2.0,3.0,2.0,2561.0,2.0,2.0,1,5.0,2.0,2.0
3,2.0,2,73,1.0,1,2.0,2.0,2.0,3.0,1.0,2330.0,2.0,1.0,1,7.0,1.0,2.0
4,2.0,2,43,4.0,2,2.0,2.0,2.0,3.0,2.0,2177.0,2.0,2.0,1,9.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445127,2.0,2,19,3.0,1,2.0,2.0,2.0,3.0,2.0,2563.0,2.0,2.0,2,6.0,1.0,1.0
445128,2.0,2,51,1.0,2,2.0,2.0,2.0,3.0,2.0,2866.0,2.0,2.0,2,7.0,2.0,2.0
445129,2.0,2,65,5.0,3,2.0,2.0,2.0,3.0,2.0,1723.0,2.0,1.0,2,5.0,2.0,2.0
445130,1.0,1,73,2.0,1,2.0,2.0,2.0,3.0,2.0,3255.0,2.0,2.0,2,5.0,1.0,2.0
445131,2.0,1,42,2.0,1,2.0,2.0,2.0,3.0,2.0,2260.0,1.0,1.0,2,5.0,2.0,2.0

In [6]:
brfss_reduced['HEALTH'] = brfss_reduced['HEALTH'].replace({7: '', 9: ''})
brfss_reduced['PHYSICAL_HEALTH'] = brfss_reduced['PHYSICAL_HEALTH'].replace({7: '', 9: ''})
brfss_reduced['BRONCHITIS'] = brfss_reduced['BRONCHITIS'].replace({7: '', 9: ''})
brfss_reduced['KIDNEY_DISEASE'] = brfss_reduced['KIDNEY_DISEASE'].replace({7: '', 9: ''})
brfss_reduced['DIABETES'] = brfss_reduced['DIABETES'].replace({7: '', 9: ''})
brfss_reduced['DIFFICULTY_WALKING'] = brfss_reduced['DIFFICULTY_WALKING'].replace({7: '', 9: ''})
brfss_reduced['SMOKE'] = brfss_reduced['SMOKE'].replace({7: '', 9: ''})
brfss_reduced['STROKE'] = brfss_reduced['STROKE'].replace({7: '', 9: ''})
brfss_reduced['ARTHRITIS'] = brfss_reduced['ARTHRITIS'].replace({7: '', 9: ''})
brfss_reduced['ASTHMA'] = brfss_reduced['ASTHMA'].replace({7: '', 9: ''})
brfss_reduced['DEPRESSION'] = brfss_reduced['DEPRESSION'].replace({7: '', 9: ''})
brfss_reduced['SLEEP'] = brfss_reduced['SLEEP'].replace({77: '', 99: ''})

C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['HEALTH'] = brfss_reduced['HEALTH'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['PHYSICAL_HEALTH'] = brfss_reduced['PHYSICAL_HEALTH'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['BRONCHITIS'] = brfss_reduced['BRONCHITIS'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['KIDNEY_DISEASE'] = brfss_reduced['KIDNEY_DISEASE'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['DIABETES'] = brfss_reduced['DIABETES'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['DIFFICULTY_WALKING'] = brfss_reduced['DIFFICULTY_WALKING'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['SMOKE'] = brfss_reduced['SMOKE'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['STROKE'] = brfss_reduced['STROKE'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['ARTHRITIS'] = brfss_reduced['ARTHRITIS'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['ASTHMA'] = brfss_reduced['ASTHMA'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['DEPRESSION'] = brfss_reduced['DEPRESSION'].replace({7: '', 9: ''})
C:\Users\alecv\AppData\Local\Temp\ipykernel_17072\160216485.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_reduced['SLEEP'] = brfss_reduced['SLEEP'].replace({77: '', 99: ''})

In [7]:
brfss_reduced.to_csv('brfss_cleaned.csv', index=False)